### ISSUE TITLE
What happens on device rotation?

### ISSUE THREAD

**Issue by hokster7** [ddoria921/DDCoachMarks#5]

**Comment by ddoria921** [comment]
@andygeers added a modification to handle device rotation.You can find the commit [here](https://github.com/ddoria921/DDCoachMarks/commit/51e1b5de14d3012954ac09755bfd80bc0c4e68c0).

Thanks again, Andy!

**Comment by andygeers** [comment]
I also blogged about how I handle rotations here: http://www.geero.net/2015/02/adding-coach-marks-to-an-ios-app-with-ddcoachmarks/
