### ISSUE TITLE
How to lower the alpha?

### ISSUE THREAD

**Issue by maxykato** [ddoria921/DDCoachMarks#6]
I love this library over the famous WSCoachView since it has a nice bubble for captions with nice animations.

Anyway, I wanted to have less alpha for the black mask screen. 
Is it possible?

I tried as below (in Swift) but no success
I would appreciate your advice.

coachMarksView.maskView?.alpha = 0.1
coachMarksView..alpha = 0.1

**Comment by ddoria921** [comment]
The alpha is currently hard coded, but I can easily expose a variable that let's you control the alpha of the overlay.

**Comment by ddoria921** [comment]
@maxykato completely forgot that I already had this built in haha. There is a method available to the coachMarksView that allows you to set the mask color as a UIColor. You can use this to set the alpha.

In Objective-C, the method looks like `(void)setMaskColor:(UIColor *)maskColor`.

So your code would look something like this:

```
DDCoachMarksView *coachMarksView = [[DDCoachMarksView alloc] initWithFrame:self.view.bounds coachMarks:coachMarks];
[coachMarksView setMaskColor:[UIColor colorWithWhite:0.000 alpha:0.800]];

[self.view addSubview:coachMarksView];
[coachMarksView start];
```

I should probably make that method public. I believe that was my intent when I originally wrote it.

**Comment by ddoria921** [comment]
Made the method public in the latest commit.

See [latest commit here](https://github.com/ddoria921/DDCoachMarks/commit/288374f6103f6fc8dc6be61718ba88fe275d9cf4).
